complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'completion [shell-name]                   Generate codefresh completion.  [aliases: completions]'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'tag <id> [tags..]                         Add an image tag.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'untag <id> [tags..]                       Untag an image.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'run <name>                                Run a pipeline by id or name and attach the created workflow logs.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'add                                       Add a resource.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'annotate                                  Annotate a resource with labels.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'patch                                     Patch a resource by filename or stdin.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'auth                                      Manage authentication contexts.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'create                                    Create a resource from a file or stdin.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'delete                                    Delete a resource by file or resource name.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'diff                                      Show diff between two resources.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'generate                                  Generate resources as Kubernetes image pull secret and Codefresh Registry token.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'get                                       Display one or many resources.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'replace                                   Replace a resource by filename.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'synchronize                               Synchronize a resource.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'validate [filenames..]                    Validate codefresh pipeline yaml config files.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'version [component]                       Print version.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'approve <buildId>                         Approve a pending-approval workflow.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'deny <buildId>                            Deny a pending-approval workflow.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'logs <id>                                 Show logs of a build.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'restart <id>                              Restart a build by its id.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'terminate <id>                            Terminate a build by its id.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'wait <id..>                               Wait until a condition will be met on a build.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'analyze <repoOwner> <repoName> [context]  Analyzes your git repository and creates a proposed Cofefresh pipeline that clones the source code and builds/packages it.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'cli-config                                Codefresh CLI configuration. Uses profiles.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'install-chart                             Install or upgrade a Helm chart Repository flag can be either absolute url or saved repository in Codefresh.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'helm-promotion                            Promote a Helm release in another environment.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'delete-release <name>                     Delete a helm release from a kubernetes cluster.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -f -c cfr -n __fish_use_subcommand -a codefresh -d 'test-release <name>                       Test a helm release.'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -n '__fish_seen_subcommand_from codefresh' -l help -d 'Show help  [boolean]'
complete -c cfr -l cfconfig -d 'Custom path for authentication contexts config file (default: /Users/d/.cfconfig)'
complete -c cfr -l request-timeout -d 'Request timeout (default: 30000)'
complete -c cfr -l help -d 'Show help  [boolean]'
