complete -f -c chamber -n __fish_use_subcommand -a delete -d 'Delete a secret, including all versions'
complete -c chamber -n '__fish_seen_subcommand_from delete' -s h -l help -d 'help for delete'
complete -c chamber -n '__fish_seen_subcommand_from delete' -s b -l backend -d 'string             Backend to use; AKA $CHAMBER_SECRET_BACKEND'
complete -c chamber -n '__fish_seen_subcommand_from delete' -l backend-s3-bucket -d 'string   bucket for S3 backend; AKA $CHAMBER_S3_BUCKET'
complete -c chamber -n '__fish_seen_subcommand_from delete' -l kms-key-alias -d 'string       KMS Key Alias for writing and deleting secrets; AKA $CHAMBER_KMS_KEY_ALIAS. This option is currently only supported for the S3-KMS backend. (default "alias/parameter_store_key")'
complete -c chamber -n '__fish_seen_subcommand_from delete' -s r -l retries -d int\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ For\ SSM,\ the\ number\ of\ retries\ we\'ll\ make\ before\ giving\ up\ \(default\ 10\)
complete -c chamber -n '__fish_seen_subcommand_from delete' -l verbose -d 'Print more information to STDOUT'
complete -f -c chamber -n __fish_use_subcommand -a env -d 'Print the secrets from the parameter store in a format to export as environment variables'
complete -c chamber -n '__fish_seen_subcommand_from env' -s h -l help -d 'help for env'
complete -c chamber -n '__fish_seen_subcommand_from env' -s b -l backend -d 'string             Backend to use; AKA $CHAMBER_SECRET_BACKEND'
complete -c chamber -n '__fish_seen_subcommand_from env' -l backend-s3-bucket -d 'string   bucket for S3 backend; AKA $CHAMBER_S3_BUCKET'
complete -c chamber -n '__fish_seen_subcommand_from env' -l kms-key-alias -d 'string       KMS Key Alias for writing and deleting secrets; AKA $CHAMBER_KMS_KEY_ALIAS. This option is currently only supported for the S3-KMS backend. (default "alias/parameter_store_key")'
complete -c chamber -n '__fish_seen_subcommand_from env' -s r -l retries -d int\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ For\ SSM,\ the\ number\ of\ retries\ we\'ll\ make\ before\ giving\ up\ \(default\ 10\)
complete -c chamber -n '__fish_seen_subcommand_from env' -l verbose -d 'Print more information to STDOUT'
complete -f -c chamber -n __fish_use_subcommand -a export -d 'Exports parameters in the specified format'
complete -c chamber -n '__fish_seen_subcommand_from export' -s f -l format -d 'string        Output format (json, java-properties, csv, tsv, dotenv, tfvars) (default "json")'
complete -c chamber -n '__fish_seen_subcommand_from export' -s h -l help -d 'help for export'
complete -c chamber -n '__fish_seen_subcommand_from export' -s o -l output-file -d 'string   Output file (default is standard output)'
complete -c chamber -n '__fish_seen_subcommand_from export' -s b -l backend -d 'string             Backend to use; AKA $CHAMBER_SECRET_BACKEND'
complete -c chamber -n '__fish_seen_subcommand_from export' -l backend-s3-bucket -d 'string   bucket for S3 backend; AKA $CHAMBER_S3_BUCKET'
complete -c chamber -n '__fish_seen_subcommand_from export' -l kms-key-alias -d 'string       KMS Key Alias for writing and deleting secrets; AKA $CHAMBER_KMS_KEY_ALIAS. This option is currently only supported for the S3-KMS backend. (default "alias/parameter_store_key")'
complete -c chamber -n '__fish_seen_subcommand_from export' -s r -l retries -d int\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ For\ SSM,\ the\ number\ of\ retries\ we\'ll\ make\ before\ giving\ up\ \(default\ 10\)
complete -c chamber -n '__fish_seen_subcommand_from export' -l verbose -d 'Print more information to STDOUT'
complete -f -c chamber -n __fish_use_subcommand -a history -d 'View the history of a secret'
complete -c chamber -n '__fish_seen_subcommand_from history' -s h -l help -d 'help for history'
complete -c chamber -n '__fish_seen_subcommand_from history' -s b -l backend -d 'string             Backend to use; AKA $CHAMBER_SECRET_BACKEND'
complete -c chamber -n '__fish_seen_subcommand_from history' -l backend-s3-bucket -d 'string   bucket for S3 backend; AKA $CHAMBER_S3_BUCKET'
complete -c chamber -n '__fish_seen_subcommand_from history' -l kms-key-alias -d 'string       KMS Key Alias for writing and deleting secrets; AKA $CHAMBER_KMS_KEY_ALIAS. This option is currently only supported for the S3-KMS backend. (default "alias/parameter_store_key")'
complete -c chamber -n '__fish_seen_subcommand_from history' -s r -l retries -d int\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ For\ SSM,\ the\ number\ of\ retries\ we\'ll\ make\ before\ giving\ up\ \(default\ 10\)
complete -c chamber -n '__fish_seen_subcommand_from history' -l verbose -d 'Print more information to STDOUT'
complete -f -c chamber -n __fish_use_subcommand -a import -d 'import secrets from json'
complete -c chamber -n '__fish_seen_subcommand_from import' -s h -l help -d 'help for import'
complete -c chamber -n '__fish_seen_subcommand_from import' -s b -l backend -d 'string             Backend to use; AKA $CHAMBER_SECRET_BACKEND'
complete -c chamber -n '__fish_seen_subcommand_from import' -l backend-s3-bucket -d 'string   bucket for S3 backend; AKA $CHAMBER_S3_BUCKET'
complete -c chamber -n '__fish_seen_subcommand_from import' -l kms-key-alias -d 'string       KMS Key Alias for writing and deleting secrets; AKA $CHAMBER_KMS_KEY_ALIAS. This option is currently only supported for the S3-KMS backend. (default "alias/parameter_store_key")'
complete -c chamber -n '__fish_seen_subcommand_from import' -s r -l retries -d int\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ For\ SSM,\ the\ number\ of\ retries\ we\'ll\ make\ before\ giving\ up\ \(default\ 10\)
complete -c chamber -n '__fish_seen_subcommand_from import' -l verbose -d 'Print more information to STDOUT'
complete -f -c chamber -n __fish_use_subcommand -a list -d 'List the secrets set for a service'
complete -c chamber -n '__fish_seen_subcommand_from list' -s e -l expand -d 'Expand parameter list with values'
complete -c chamber -n '__fish_seen_subcommand_from list' -s h -l help -d 'help for list'
complete -c chamber -n '__fish_seen_subcommand_from list' -s t -l time -d 'Sort by modified time'
complete -c chamber -n '__fish_seen_subcommand_from list' -s u -l user -d 'Sort by user'
complete -c chamber -n __fish_no_arguments -s v -l version -d 'Sort by version'
complete -c chamber -n '__fish_seen_subcommand_from list' -s b -l backend -d 'string             Backend to use; AKA $CHAMBER_SECRET_BACKEND'
complete -c chamber -n '__fish_seen_subcommand_from list' -l backend-s3-bucket -d 'string   bucket for S3 backend; AKA $CHAMBER_S3_BUCKET'
complete -c chamber -n '__fish_seen_subcommand_from list' -l kms-key-alias -d 'string       KMS Key Alias for writing and deleting secrets; AKA $CHAMBER_KMS_KEY_ALIAS. This option is currently only supported for the S3-KMS backend. (default "alias/parameter_store_key")'
complete -c chamber -n '__fish_seen_subcommand_from list' -s r -l retries -d int\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ For\ SSM,\ the\ number\ of\ retries\ we\'ll\ make\ before\ giving\ up\ \(default\ 10\)
complete -c chamber -n '__fish_seen_subcommand_from list' -l verbose -d 'Print more information to STDOUT'
complete -f -c chamber -n __fish_use_subcommand -a read -d 'Read a specific secret from the parameter store'
complete -c chamber -n '__fish_seen_subcommand_from read' -s h -l help -d 'help for read'
complete -c chamber -n '__fish_seen_subcommand_from read' -s q -l quiet -d 'Only print the secret'
complete -c chamber -n __fish_no_arguments -s v -l version -d 'int   The version number of the secret. Defaults to latest. (default -1)'
complete -c chamber -n '__fish_seen_subcommand_from read' -s b -l backend -d 'string             Backend to use; AKA $CHAMBER_SECRET_BACKEND'
complete -c chamber -n '__fish_seen_subcommand_from read' -l backend-s3-bucket -d 'string   bucket for S3 backend; AKA $CHAMBER_S3_BUCKET'
complete -c chamber -n '__fish_seen_subcommand_from read' -l kms-key-alias -d 'string       KMS Key Alias for writing and deleting secrets; AKA $CHAMBER_KMS_KEY_ALIAS. This option is currently only supported for the S3-KMS backend. (default "alias/parameter_store_key")'
complete -c chamber -n '__fish_seen_subcommand_from read' -s r -l retries -d int\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ For\ SSM,\ the\ number\ of\ retries\ we\'ll\ make\ before\ giving\ up\ \(default\ 10\)
complete -c chamber -n '__fish_seen_subcommand_from read' -l verbose -d 'Print more information to STDOUT'
complete -f -c chamber -n __fish_use_subcommand -a version -d 'print version'
complete -c chamber -n '__fish_seen_subcommand_from version' -s h -l help -d 'help for version'
complete -c chamber -n '__fish_seen_subcommand_from version' -s b -l backend -d 'string             Backend to use; AKA $CHAMBER_SECRET_BACKEND'
complete -c chamber -n '__fish_seen_subcommand_from version' -l backend-s3-bucket -d 'string   bucket for S3 backend; AKA $CHAMBER_S3_BUCKET'
complete -c chamber -n '__fish_seen_subcommand_from version' -l kms-key-alias -d 'string       KMS Key Alias for writing and deleting secrets; AKA $CHAMBER_KMS_KEY_ALIAS. This option is currently only supported for the S3-KMS backend. (default "alias/parameter_store_key")'
complete -c chamber -n '__fish_seen_subcommand_from version' -s r -l retries -d int\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ For\ SSM,\ the\ number\ of\ retries\ we\'ll\ make\ before\ giving\ up\ \(default\ 10\)
complete -c chamber -n '__fish_seen_subcommand_from version' -l verbose -d 'Print more information to STDOUT'
complete -f -c chamber -n __fish_use_subcommand -a write -d 'write a secret'
complete -c chamber -n '__fish_seen_subcommand_from write' -s h -l help -d 'help for write'
complete -c chamber -n '__fish_seen_subcommand_from write' -s s -l singleline -d Insert\ single\ line\ parameter\ \(end\ with\ \\n\)
complete -c chamber -n '__fish_seen_subcommand_from write' -l skip-unchanged -d 'Skip writing secret if value is unchanged'
complete -c chamber -n '__fish_seen_subcommand_from write' -s b -l backend -d 'string             Backend to use; AKA $CHAMBER_SECRET_BACKEND'
complete -c chamber -n '__fish_seen_subcommand_from write' -l backend-s3-bucket -d 'string   bucket for S3 backend; AKA $CHAMBER_S3_BUCKET'
complete -c chamber -n '__fish_seen_subcommand_from write' -l kms-key-alias -d 'string       KMS Key Alias for writing and deleting secrets; AKA $CHAMBER_KMS_KEY_ALIAS. This option is currently only supported for the S3-KMS backend. (default "alias/parameter_store_key")'
complete -c chamber -n '__fish_seen_subcommand_from write' -s r -l retries -d int\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ For\ SSM,\ the\ number\ of\ retries\ we\'ll\ make\ before\ giving\ up\ \(default\ 10\)
complete -c chamber -n '__fish_seen_subcommand_from write' -l verbose -d 'Print more information to STDOUT'
complete -c chamber -s b -l backend -d 'string             Backend to use; AKA $CHAMBER_SECRET_BACKEND'
complete -c chamber -l backend-s3-bucket -d 'string   bucket for S3 backend; AKA $CHAMBER_S3_BUCKET'
complete -c chamber -s h -l help -d 'help for chamber'
complete -c chamber -l kms-key-alias -d 'string       KMS Key Alias for writing and deleting secrets; AKA $CHAMBER_KMS_KEY_ALIAS. This option is currently only supported for the S3-KMS backend. (default "alias/parameter_store_key")'
complete -c chamber -s r -l retries -d int\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ For\ SSM,\ the\ number\ of\ retries\ we\'ll\ make\ before\ giving\ up\ \(default\ 10\)
complete -c chamber -l verbose -d 'Print more information to STDOUT'
