complete -f -c chezmoi -n __fish_use_subcommand -a add -d 'Add an existing file, directory, or symlink to the source state'
complete -c chezmoi -n '__fish_seen_subcommand_from add' -s a -l autotemplate -d 'auto generate the template when adding files as templates'
complete -c chezmoi -n '__fish_seen_subcommand_from add' -s e -l empty -d 'add empty files'
complete -c chezmoi -n '__fish_seen_subcommand_from add' -l encrypt -d 'encrypt files'
complete -c chezmoi -n '__fish_seen_subcommand_from add' -s x -l exact -d 'add directories exactly'
complete -c chezmoi -n '__fish_seen_subcommand_from add' -s h -l help -d 'help for add'
complete -c chezmoi -n '__fish_seen_subcommand_from add' -s p -l prompt -d 'prompt before adding'
complete -c chezmoi -n '__fish_seen_subcommand_from add' -s r -l recursive -d 'recurse in to subdirectories'
complete -c chezmoi -n '__fish_seen_subcommand_from add' -s T -l template -d 'add files as templates'
complete -c chezmoi -n '__fish_seen_subcommand_from add' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from add' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from add' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from add' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from add' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from add' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from add' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from add' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a apply -d 'Update the destination directory to match the target state'
complete -c chezmoi -n '__fish_seen_subcommand_from apply' -s h -l help -d 'help for apply'
complete -c chezmoi -n '__fish_seen_subcommand_from apply' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from apply' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from apply' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from apply' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from apply' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from apply' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from apply' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from apply' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a archive -d 'Write a tar archive of the target state to stdout'
complete -c chezmoi -n '__fish_seen_subcommand_from archive' -s h -l help -d 'help for archive'
complete -c chezmoi -n '__fish_seen_subcommand_from archive' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from archive' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from archive' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from archive' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from archive' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from archive' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from archive' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from archive' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a cat -d 'Write the target state of a file or symlink to stdout'
complete -c chezmoi -n '__fish_seen_subcommand_from cat' -s h -l help -d 'help for cat'
complete -c chezmoi -n '__fish_seen_subcommand_from cat' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from cat' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from cat' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from cat' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from cat' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from cat' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from cat' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from cat' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a cd -d 'Launch a shell in the source directory'
complete -c chezmoi -n '__fish_seen_subcommand_from cd' -s h -l help -d 'help for cd'
complete -c chezmoi -n '__fish_seen_subcommand_from cd' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from cd' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from cd' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from cd' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from cd' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from cd' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from cd' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from cd' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a chattr -d 'Change the attributes of a target in the source state'
complete -c chezmoi -n '__fish_seen_subcommand_from chattr' -s h -l help -d 'help for chattr'
complete -c chezmoi -n '__fish_seen_subcommand_from chattr' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from chattr' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from chattr' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from chattr' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from chattr' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from chattr' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from chattr' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from chattr' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a completion -d 'Output shell completion code for the specified shell (bash, fish or zsh)'
complete -c chezmoi -n '__fish_seen_subcommand_from completion' -s h -l help -d 'help for completion'
complete -c chezmoi -n '__fish_seen_subcommand_from completion' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from completion' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from completion' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from completion' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from completion' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from completion' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from completion' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from completion' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a data -d 'Write the template data to stdout'
complete -c chezmoi -n '__fish_seen_subcommand_from data' -s f -l format -d 'string   format (JSON, TOML, or YAML) (default "json")'
complete -c chezmoi -n '__fish_seen_subcommand_from data' -s h -l help -d 'help for data'
complete -c chezmoi -n '__fish_seen_subcommand_from data' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from data' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from data' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from data' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from data' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from data' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from data' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from data' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a diff -d 'Write the diff between the target state and the destination state to stdout'
complete -c chezmoi -n '__fish_seen_subcommand_from diff' -l dry-run -d '--verbose".'
complete -c chezmoi -n '__fish_seen_subcommand_from diff' -s h -l help -d 'help for diff'
complete -c chezmoi -n '__fish_seen_subcommand_from diff' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from diff' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from diff' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from diff' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from diff' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from diff' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from diff' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from diff' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a docs -d 'Print documentation'
complete -c chezmoi -n '__fish_seen_subcommand_from docs' -s h -l help -d 'help for docs'
complete -c chezmoi -n '__fish_seen_subcommand_from docs' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from docs' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from docs' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from docs' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from docs' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from docs' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from docs' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from docs' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a doctor -d 'Check your system for potential problems'
complete -c chezmoi -n '__fish_seen_subcommand_from doctor' -s h -l help -d 'help for doctor'
complete -c chezmoi -n '__fish_seen_subcommand_from doctor' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from doctor' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from doctor' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from doctor' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from doctor' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from doctor' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from doctor' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from doctor' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a dump -d 'Write a dump of the target state to stdout'
complete -c chezmoi -n '__fish_seen_subcommand_from dump' -s f -l format -d 'string   format (JSON, TOML, or YAML) (default "json")'
complete -c chezmoi -n '__fish_seen_subcommand_from dump' -s h -l help -d 'help for dump'
complete -c chezmoi -n '__fish_seen_subcommand_from dump' -s r -l recursive -d 'recursive (default true)'
complete -c chezmoi -n '__fish_seen_subcommand_from dump' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from dump' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from dump' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from dump' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from dump' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from dump' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from dump' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from dump' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a edit -d 'Edit the source state of a target'
complete -c chezmoi -n '__fish_seen_subcommand_from edit' -s a -l apply -d 'apply edit after editing'
complete -c chezmoi -n '__fish_seen_subcommand_from edit' -s d -l diff -d 'print diff after editing'
complete -c chezmoi -n '__fish_seen_subcommand_from edit' -s h -l help -d 'help for edit'
complete -c chezmoi -n '__fish_seen_subcommand_from edit' -s p -l prompt -d 'prompt before applying (implies --diff)'
complete -c chezmoi -n '__fish_seen_subcommand_from edit' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from edit' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from edit' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from edit' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from edit' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from edit' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from edit' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from edit' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a edit-config -d 'Edit the configuration file'
complete -c chezmoi -n '__fish_seen_subcommand_from edit-config' -s h -l help -d 'help for edit-config'
complete -c chezmoi -n '__fish_seen_subcommand_from edit-config' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from edit-config' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from edit-config' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from edit-config' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from edit-config' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from edit-config' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from edit-config' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from edit-config' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a forget -d 'Remove a target from the source state'
complete -c chezmoi -n '__fish_seen_subcommand_from forget' -s h -l help -d 'help for forget'
complete -c chezmoi -n '__fish_seen_subcommand_from forget' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from forget' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from forget' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from forget' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from forget' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from forget' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from forget' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from forget' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a import -d 'Import a tar archive into the source state'
complete -c chezmoi -n '__fish_seen_subcommand_from import' -s x -l exact -d 'import directories exactly'
complete -c chezmoi -n '__fish_seen_subcommand_from import' -s h -l help -d 'help for import'
complete -c chezmoi -n '__fish_seen_subcommand_from import' -s r -l remove-destination -d 'remove destination before import'
complete -c chezmoi -n '__fish_seen_subcommand_from import' -l strip-components -d 'int   strip components'
complete -c chezmoi -n '__fish_seen_subcommand_from import' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from import' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from import' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from import' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from import' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from import' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from import' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from import' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a init -d 'Setup the source directory and update the destination directory to match the target state'
complete -c chezmoi -n '__fish_seen_subcommand_from init' -l apply -d 'update destination directory'
complete -c chezmoi -n '__fish_seen_subcommand_from init' -s h -l help -d 'help for init'
complete -c chezmoi -n '__fish_seen_subcommand_from init' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from init' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from init' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from init' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from init' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from init' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from init' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from init' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a merge -d 'Perform a three-way merge between the destination state, the source state, and the target state'
complete -c chezmoi -n '__fish_seen_subcommand_from merge' -s h -l help -d 'help for merge'
complete -c chezmoi -n '__fish_seen_subcommand_from merge' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from merge' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from merge' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from merge' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from merge' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from merge' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from merge' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from merge' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a remove -d 'Remove a target from the source state and the destination directory'
complete -c chezmoi -n '__fish_seen_subcommand_from remove' -s f -l force -d 'remove without prompting'
complete -c chezmoi -n '__fish_seen_subcommand_from remove' -s h -l help -d 'help for remove'
complete -c chezmoi -n '__fish_seen_subcommand_from remove' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from remove' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from remove' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from remove' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from remove' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from remove' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from remove' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from remove' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a secret -d 'Interact with a secret manager'
complete -c chezmoi -n '__fish_seen_subcommand_from secret' -s h -l help -d 'help for secret'
complete -c chezmoi -n '__fish_seen_subcommand_from secret' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from secret' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from secret' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from secret' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from secret' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from secret' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from secret' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from secret' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a source-path -d 'Print the path of a target in the source state'
complete -c chezmoi -n '__fish_seen_subcommand_from source-path' -s h -l help -d 'help for source-path'
complete -c chezmoi -n '__fish_seen_subcommand_from source-path' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from source-path' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from source-path' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from source-path' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from source-path' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from source-path' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from source-path' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from source-path' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a unmanaged -d 'List the unmanaged files in the destination directory'
complete -c chezmoi -n '__fish_seen_subcommand_from unmanaged' -s h -l help -d 'help for unmanaged'
complete -c chezmoi -n '__fish_seen_subcommand_from unmanaged' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from unmanaged' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from unmanaged' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from unmanaged' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from unmanaged' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from unmanaged' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from unmanaged' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from unmanaged' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a update -d 'Pull changes from the source VCS and apply any changes'
complete -c chezmoi -n '__fish_seen_subcommand_from update' -s a -l apply -d 'apply after pulling (default true)'
complete -c chezmoi -n '__fish_seen_subcommand_from update' -s h -l help -d 'help for update'
complete -c chezmoi -n '__fish_seen_subcommand_from update' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from update' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from update' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from update' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from update' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from update' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from update' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from update' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a upgrade -d 'Upgrade chezmoi'
complete -c chezmoi -n '__fish_seen_subcommand_from upgrade' -s f -l force -d 'force upgrade'
complete -c chezmoi -n '__fish_seen_subcommand_from upgrade' -s h -l help -d 'help for upgrade'
complete -c chezmoi -n '__fish_seen_subcommand_from upgrade' -s m -l method -d 'string   set method'
complete -c chezmoi -n '__fish_seen_subcommand_from upgrade' -s o -l owner -d 'string    set owner (default "twpayne")'
complete -c chezmoi -n '__fish_seen_subcommand_from upgrade' -s r -l repo -d 'string     set repo (default "chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from upgrade' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from upgrade' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from upgrade' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from upgrade' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from upgrade' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from upgrade' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from upgrade' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from upgrade' -s v -l verbose -d verbose
complete -f -c chezmoi -n __fish_use_subcommand -a verify -d 'Exit with success if the destination state matches the target state, fail otherwise'
complete -c chezmoi -n '__fish_seen_subcommand_from verify' -s h -l help -d 'help for verify'
complete -c chezmoi -n '__fish_seen_subcommand_from verify' -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -n '__fish_seen_subcommand_from verify' -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -n '__fish_seen_subcommand_from verify' -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -n '__fish_seen_subcommand_from verify' -s n -l dry-run -d 'dry run'
complete -c chezmoi -n '__fish_seen_subcommand_from verify' -l follow -d 'follow symlinks'
complete -c chezmoi -n '__fish_seen_subcommand_from verify' -l remove -d 'remove targets'
complete -c chezmoi -n '__fish_seen_subcommand_from verify' -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -n '__fish_seen_subcommand_from verify' -s v -l verbose -d verbose
complete -c chezmoi -l color -d 'string         colorize diffs (default "auto")'
complete -c chezmoi -s c -l config -d 'string        config file (default "/Users/d/.config/chezmoi/chezmoi.toml")'
complete -c chezmoi -s D -l destination -d 'string   destination directory (default "/Users/d")'
complete -c chezmoi -s n -l dry-run -d 'dry run'
complete -c chezmoi -l follow -d 'follow symlinks'
complete -c chezmoi -s h -l help -d 'help for chezmoi'
complete -c chezmoi -l remove -d 'remove targets'
complete -c chezmoi -s S -l source -d 'string        source directory (default "/Users/d/.local/share/chezmoi")'
complete -c chezmoi -s v -l verbose -d verbose
complete -c chezmoi -n __fish_no_arguments -l version -d 'version for chezmoi'
