complete -f -c corgi -n __fish_use_subcommand -a config -d 'Update corgi configuration'
complete -c corgi -n '__fish_seen_subcommand_from config' -l editor -d 'string         Set the text editor you would like to use to edit snippet'
complete -c corgi -n '__fish_seen_subcommand_from config' -l filter-cmd -d 'string     Set the filter command to use for fuzzy searching snippet (default to fzf)'
complete -c corgi -n '__fish_seen_subcommand_from config' -s h -l help -d 'help for config'
complete -c corgi -n '__fish_seen_subcommand_from config' -l snippets-dir -d 'string   Set the path where all snippets are located'
complete -f -c corgi -n __fish_use_subcommand -a describe -d 'Describe a snippet'
complete -c corgi -n '__fish_seen_subcommand_from describe' -s h -l help -d 'help for describe'
complete -f -c corgi -n __fish_use_subcommand -a edit -d 'Edit a snippet'
complete -c corgi -n '__fish_seen_subcommand_from edit' -s h -l help -d 'help for edit'
complete -f -c corgi -n __fish_use_subcommand -a exec -d 'Execute a snippet'
complete -c corgi -n '__fish_seen_subcommand_from exec' -s h -l help -d 'help for exec'
complete -c corgi -n '__fish_seen_subcommand_from exec' -s s -l step -d 'string   Select a single step to execute with "-s <step>" or a range of steps to execute with "-s <start>-<end>", end is optional'
complete -c corgi -n '__fish_seen_subcommand_from exec' -l use-default -d 'Add this flag if you would like to use the default values for your defined template fields without being asked to enter a value'
complete -f -c corgi -n __fish_use_subcommand -a export -d 'Export a snippet to json file'
complete -c corgi -n '__fish_seen_subcommand_from export' -s h -l help -d 'help for export'
complete -c corgi -n '__fish_seen_subcommand_from export' -s o -l output -d 'string   Specify the output path of the snippet'
complete -c corgi -n '__fish_seen_subcommand_from export' -s t -l type -d 'string     Choose export file type. Allowed values are: "json", "shell". (default "json")'
complete -f -c corgi -n __fish_use_subcommand -a import -d 'Import a snippet from one or multiple json files'
complete -c corgi -n '__fish_seen_subcommand_from import' -s h -l help -d 'help for import'
complete -f -c corgi -n __fish_use_subcommand -a list -d 'List all snippets'
complete -c corgi -n '__fish_seen_subcommand_from list' -s h -l help -d 'help for list'
complete -f -c corgi -n __fish_use_subcommand -a new -d 'Create a new corgi snippet'
complete -c corgi -n '__fish_seen_subcommand_from new' -s h -l help -d 'help for new'
complete -c corgi -n '__fish_seen_subcommand_from new' -s l -l last -d int\ \ \ \ \ \ \ The\ number\ of\ history\ commands\ to\ look\ back,\ they\'ll\ be\ the\ default\ for\ each\ step.\ If\ 0\ or\ unspecified,\ each\ step\ will\ not\ have\ a\ default.
complete -c corgi -n '__fish_seen_subcommand_from new' -s t -l title -d 'string   Title of the snippet, do not put any whitespace if you plan to use this snippet for composition'
complete -f -c corgi -n __fish_use_subcommand -a remove -d 'Remove a snippet'
complete -c corgi -n '__fish_seen_subcommand_from remove' -s h -l help -d 'help for remove'
complete -c corgi -s h -l help -d 'help for corgi'
complete -c corgi -n __fish_no_arguments -l version -d 'version for corgi'
