complete -c dscl -s u -d '<user>      authenticate as user (required when using DS Proxy)'
complete -c dscl -s P -d '<password>  authentication password'
complete -c dscl -s p -d 'prompt for password'
complete -c dscl -s f -d '<filepath>  targeted file path for DS daemon running in localonly mode'
complete -c dscl -s raw -d don\'t\ strip\ off\ prefix\ from\ DS\ constants
complete -c dscl -s plist -d 'print out record(s) or attribute(s) in XML plist format'
complete -c dscl -s url -d 'print record attribute values in URL-style encoding'
complete -c dscl -s q -d 'quiet - no interactive prompt'
complete -f -c dscl -n __fish_use_subcommand -a -read -d '<path> [<key>...]'
complete -f -c dscl -n __fish_use_subcommand -a -readall -d '<path> [<key>...]'
complete -f -c dscl -n __fish_use_subcommand -a -readpl -d '<path> <key> <plist path>'
complete -f -c dscl -n __fish_use_subcommand -a -readpli -d '<path> <key> <value index> <plist path>'
complete -f -c dscl -n __fish_use_subcommand -a -create -d '<record path> [<key> [<val>...]]'
complete -f -c dscl -n __fish_use_subcommand -a -createpl -d '<record path> <key> <plist path> <val1> [<val2>...]'
complete -f -c dscl -n __fish_use_subcommand -a -createpli -d '<record path> <key> <value index> <plist path> <val1> [<val2>...]'
complete -f -c dscl -n __fish_use_subcommand -a -delete -d '<path> [<key> [<val>...]]'
complete -f -c dscl -n __fish_use_subcommand -a -deletepl -d '<record path> <key> <plist path> [<val>...]'
complete -f -c dscl -n __fish_use_subcommand -a -deletepli -d '<record path> <key> <value index> <plist path> [<val>...]'
complete -f -c dscl -n __fish_use_subcommand -a -list -d '<path> [<key>]'
complete -f -c dscl -n __fish_use_subcommand -a -append -d '<record path> <key> <val>...'
complete -f -c dscl -n __fish_use_subcommand -a -merge -d '<record path> <key> <val>...'
complete -f -c dscl -n __fish_use_subcommand -a -change -d '<record path> <key> <old value> <new value>'
complete -f -c dscl -n __fish_use_subcommand -a -changei -d '<record path> <key> <value index> <new value>'
complete -f -c dscl -n __fish_use_subcommand -a -diff -d '<first path> <second path>'
complete -f -c dscl -n __fish_use_subcommand -a -search -d '<path> <key> <val>'
complete -f -c dscl -n __fish_use_subcommand -a -auth -d '[<user> [<password>]]'
complete -f -c dscl -n __fish_use_subcommand -a -authonly -d '[<user> [<password>]]'
complete -f -c dscl -n __fish_use_subcommand -a -passwd -d '<user path> [<new password> | <old password> <new password>]'
complete -c dscl -s profileimport -d '<record path> <profile file path>'
complete -c dscl -s profiledelete -d '<record path> <profile specifier>'
complete -c dscl -s profilelist -d '<record path> [optArgs]'
complete -c dscl -s profileexport -d '<record path> <profile specifier> <output folder path>'
complete -c dscl -s mcxread -d '<record path> [optArgs] [<appDomain> [<keyName>]]'
complete -c dscl -s mcxset -d '<record path> [optArgs] <appDomain> <keyName> [<mcxDomain> [<keyValue>]]'
complete -c dscl -s mcxedit -d '<record path> [optArgs] <appDomain> <keyPath> [<keyValue>]'
complete -c dscl -s mcxdelete -d '<record path> [optArgs] [<appDomain> [<keyName>]]'
complete -c dscl -s mcxdeleteall -d '<record path> [optArgs] [<appDomain> [<keyName>]]'
complete -c dscl -s mcxexport -d '<record path> [optArgs] [<appDomain> [<keyName>]]'
complete -c dscl -s mcximport -d '<record path> [optArgs] <file path>'
