complete -f -c dxcli -n __fish_use_subcommand -a account -d 'Display account information'
complete -c dxcli -n '__fish_seen_subcommand_from account' -s h -l help -d 'help for account'
complete -c dxcli -n '__fish_seen_subcommand_from account' -l as-member -d 'string   Member ID to perform action as'
complete -c dxcli -n '__fish_seen_subcommand_from account' -s v -l verbose -d 'Enable verbose logging'
complete -f -c dxcli -n __fish_use_subcommand -a cp -d Copy\ a\ file\ or\ folder\ to\ a\ different\ location\ in\ the\ user\'s\ Dropbox.\ If\ the\ source\ path\ is\ a\ folder\ all\ its\ contents\ will\ be\ copied.
complete -c dxcli -n '__fish_seen_subcommand_from cp' -s h -l help -d 'help for cp'
complete -c dxcli -n '__fish_seen_subcommand_from cp' -l as-member -d 'string   Member ID to perform action as'
complete -c dxcli -n '__fish_seen_subcommand_from cp' -s v -l verbose -d 'Enable verbose logging'
complete -f -c dxcli -n __fish_use_subcommand -a du -d 'Display usage information'
complete -c dxcli -n '__fish_seen_subcommand_from du' -s h -l help -d 'help for du'
complete -c dxcli -n '__fish_seen_subcommand_from du' -l as-member -d 'string   Member ID to perform action as'
complete -c dxcli -n '__fish_seen_subcommand_from du' -s v -l verbose -d 'Enable verbose logging'
complete -f -c dxcli -n __fish_use_subcommand -a get -d 'Download a file'
complete -c dxcli -n '__fish_seen_subcommand_from get' -s h -l help -d 'help for get'
complete -c dxcli -n '__fish_seen_subcommand_from get' -l as-member -d 'string   Member ID to perform action as'
complete -c dxcli -n '__fish_seen_subcommand_from get' -s v -l verbose -d 'Enable verbose logging'
complete -f -c dxcli -n __fish_use_subcommand -a logout -d 'Log out of the current session'
complete -c dxcli -n '__fish_seen_subcommand_from logout' -s h -l help -d 'help for logout'
complete -c dxcli -n '__fish_seen_subcommand_from logout' -l as-member -d 'string   Member ID to perform action as'
complete -c dxcli -n '__fish_seen_subcommand_from logout' -s v -l verbose -d 'Enable verbose logging'
complete -f -c dxcli -n __fish_use_subcommand -a ls -d 'List files and folders'
complete -c dxcli -n '__fish_seen_subcommand_from ls' -s h -l help -d 'help for ls'
complete -c dxcli -n '__fish_seen_subcommand_from ls' -s l -l long -d 'Long listing'
complete -c dxcli -n '__fish_seen_subcommand_from ls' -s R -l recurse -d 'Recursively list all subfolders'
complete -c dxcli -n '__fish_seen_subcommand_from ls' -l as-member -d 'string   Member ID to perform action as'
complete -c dxcli -n '__fish_seen_subcommand_from ls' -s v -l verbose -d 'Enable verbose logging'
complete -f -c dxcli -n __fish_use_subcommand -a mkdir -d 'Create a new directory'
complete -c dxcli -n '__fish_seen_subcommand_from mkdir' -s h -l help -d 'help for mkdir'
complete -c dxcli -n '__fish_seen_subcommand_from mkdir' -l as-member -d 'string   Member ID to perform action as'
complete -c dxcli -n '__fish_seen_subcommand_from mkdir' -s v -l verbose -d 'Enable verbose logging'
complete -f -c dxcli -n __fish_use_subcommand -a mv -d 'Move files'
complete -c dxcli -n '__fish_seen_subcommand_from mv' -s h -l help -d 'help for mv'
complete -c dxcli -n '__fish_seen_subcommand_from mv' -l as-member -d 'string   Member ID to perform action as'
complete -c dxcli -n '__fish_seen_subcommand_from mv' -s v -l verbose -d 'Enable verbose logging'
complete -f -c dxcli -n __fish_use_subcommand -a put -d 'Upload files'
complete -c dxcli -n '__fish_seen_subcommand_from put' -s h -l help -d 'help for put'
complete -c dxcli -n '__fish_seen_subcommand_from put' -l as-member -d 'string   Member ID to perform action as'
complete -c dxcli -n '__fish_seen_subcommand_from put' -s v -l verbose -d 'Enable verbose logging'
complete -f -c dxcli -n __fish_use_subcommand -a restore -d 'Restore files'
complete -c dxcli -n '__fish_seen_subcommand_from restore' -s h -l help -d 'help for restore'
complete -c dxcli -n '__fish_seen_subcommand_from restore' -l as-member -d 'string   Member ID to perform action as'
complete -c dxcli -n '__fish_seen_subcommand_from restore' -s v -l verbose -d 'Enable verbose logging'
complete -f -c dxcli -n __fish_use_subcommand -a revs -d 'List file revisions'
complete -c dxcli -n '__fish_seen_subcommand_from revs' -s h -l help -d 'help for revs'
complete -c dxcli -n '__fish_seen_subcommand_from revs' -s l -l long -d 'Long listing'
complete -c dxcli -n '__fish_seen_subcommand_from revs' -l as-member -d 'string   Member ID to perform action as'
complete -c dxcli -n '__fish_seen_subcommand_from revs' -s v -l verbose -d 'Enable verbose logging'
complete -f -c dxcli -n __fish_use_subcommand -a rm -d 'Remove files'
complete -c dxcli -n '__fish_seen_subcommand_from rm' -s f -l force -d 'Force removal'
complete -c dxcli -n '__fish_seen_subcommand_from rm' -s h -l help -d 'help for rm'
complete -c dxcli -n '__fish_seen_subcommand_from rm' -l as-member -d 'string   Member ID to perform action as'
complete -c dxcli -n '__fish_seen_subcommand_from rm' -s v -l verbose -d 'Enable verbose logging'
complete -f -c dxcli -n __fish_use_subcommand -a search -d Search
complete -c dxcli -n '__fish_seen_subcommand_from search' -s h -l help -d 'help for search'
complete -c dxcli -n '__fish_seen_subcommand_from search' -s l -l long -d 'Long listing'
complete -c dxcli -n '__fish_seen_subcommand_from search' -l as-member -d 'string   Member ID to perform action as'
complete -c dxcli -n '__fish_seen_subcommand_from search' -s v -l verbose -d 'Enable verbose logging'
complete -f -c dxcli -n __fish_use_subcommand -a version -d 'Print version information'
complete -c dxcli -n '__fish_seen_subcommand_from version' -s h -l help -d 'help for version'
complete -c dxcli -n '__fish_seen_subcommand_from version' -l as-member -d 'string   Member ID to perform action as'
complete -c dxcli -n '__fish_seen_subcommand_from version' -s v -l verbose -d 'Enable verbose logging'
complete -c dxcli -l as-member -d 'string   Member ID to perform action as'
complete -c dxcli -s h -l help -d 'help for dbxcli'
complete -c dxcli -s v -l verbose -d 'Enable verbose logging'
