complete -c fzf -s x -l extended -d 'Extended-search mode'
complete -c fzf -s e -l exact -d 'Enable Exact-match'
complete -c fzf -s i -d 'Case-insensitive match (default: smart-case match)'
complete -c fzf -l literal -d 'Do not normalize latin script letters before matching'
complete -c fzf -l tac -d 'Reverse the order of the input'
complete -c fzf -s m -l multi -d 'Enable multi-select with tab/shift-tab'
complete -c fzf -l no-mouse -d 'Disable mouse'
complete -c fzf -l cycle -d 'Enable cyclic scroll'
complete -c fzf -l no-hscroll -d 'Disable horizontal scroll'
complete -c fzf -l filepath-word -d 'Make word-wise movements respect path separators'
complete -c fzf -l border -d 'Draw border above and below the finder'
complete -c fzf -l inline-info -d 'Display finder info inline with the query'
complete -c fzf -l ansi -d 'Enable processing of ANSI color codes'
complete -c fzf -l no-bold -d 'Do not use bold text'
complete -c fzf -s 1 -l select-1 -d 'Automatically select the only match'
complete -c fzf -s 0 -l exit-0 -d Exit\ immediately\ when\ there\'s\ no\ match
complete -c fzf -l print-query -d 'Print query as the first line'
complete -c fzf -l read0 -d 'Read input delimited by ASCII NUL characters'
complete -c fzf -l print0 -d 'Print output delimited by ASCII NUL characters'
complete -c fzf -l sync -d 'Synchronous search for multi-staged filtering'
complete -c fzf -n __fish_no_arguments -l version -d 'Display version information and exit'
complete -f -c fzf -n __fish_use_subcommand -a FZF_DEFAULT_OPTS -d 'Default options'
