complete -c gencomp -s d -l dry-run -d 'print completions without execution'
complete -c gencomp -l edit -d 'edit a generated completion'
complete -c gencomp -l erase -d 'erase generated completions'
complete -c gencomp -s l -l list -d 'list generated completions'
complete -c gencomp -s r -l root -d 'print the directory to save completions'
complete -c gencomp -s S -l subcommands -d 'generate completion for subcommands'
complete -c gencomp -s u -l use -d 'use the specified command to get usage'
complete -c gencomp -s w -l wraps -d 'inherit existing completions'
complete -c gencomp -s h -l help -d 'show this help'
