complete -f -c ghq -n __fish_use_subcommand -a get -d 'Clone/sync with a remote repository'
complete -c ghq -n '__fish_seen_subcommand_from get' -s u -l update -d 'Update local repository if cloned already'
complete -c ghq -n '__fish_seen_subcommand_from get' -s p -d 'Clone with SSH'
complete -c ghq -n '__fish_seen_subcommand_from get' -l shallow -d 'Do a shallow clone'
complete -c ghq -n '__fish_seen_subcommand_from get' -s l -l look -d 'Look after get'
complete -c ghq -n '__fish_seen_subcommand_from get' -l vcs -d 'value   Specify VCS backend for cloning'
complete -c ghq -n '__fish_seen_subcommand_from get' -s s -l silent -d 'clone or update silently'
complete -f -c ghq -n __fish_use_subcommand -a list -d 'List local repositories'
complete -c ghq -n '__fish_seen_subcommand_from list' -s e -l exact -d 'Perform an exact match'
complete -c ghq -n '__fish_seen_subcommand_from list' -l vcs -d 'value      Specify VCS backend for matching'
complete -c ghq -n '__fish_seen_subcommand_from list' -s p -l full-path -d 'Print full paths'
complete -c ghq -n '__fish_seen_subcommand_from list' -l unique -d 'Print unique subpaths'
complete -f -c ghq -n __fish_use_subcommand -a look -d 'Look into a local repository'
complete -x -c ghq -n '__fish_seen_subcommand_from look' -a "( ls $GH_BASE_DIR)" -d 'username'
complete -f -c ghq -n __fish_use_subcommand -a import -d 'Bulk get repositories from stdin'
complete -c ghq -n '__fish_seen_subcommand_from import' -s u -l update -d 'Update local repository if cloned already'
complete -c ghq -n '__fish_seen_subcommand_from import' -s p -d 'Clone with SSH'
complete -c ghq -n '__fish_seen_subcommand_from import' -l shallow -d 'Do a shallow clone'
complete -c ghq -n '__fish_seen_subcommand_from import' -s l -l look -d 'Look after get'
complete -c ghq -n '__fish_seen_subcommand_from import' -l vcs -d 'value     Specify VCS backend for cloning'
complete -c ghq -n '__fish_seen_subcommand_from import' -s s -l silent -d 'clone or update silently'
complete -c ghq -n '__fish_seen_subcommand_from import' -s P -l parallel -d '[Experimental] Import parallely'
complete -f -c ghq -n __fish_use_subcommand -a root -d Show\ repositories\'\ root
complete -c ghq -n '__fish_seen_subcommand_from root' -l all -d 'Show all roots'
complete -f -c ghq -n __fish_use_subcommand -a help -d 'Shows a list of commands or help for one command'
complete -c ghq -s h -l help -d 'show help'
complete -c ghq -n __fish_no_arguments -s v -l version -d 'print the version'
