complete -f -c gist -n __fish_use_subcommand -a config -d 'Config the setting file'
complete -c gist -n '__fish_seen_subcommand_from config' -s h -l help -d 'help for config'
complete -f -c gist -n __fish_use_subcommand -a delete -d 'Delete gist files'
complete -c gist -n '__fish_seen_subcommand_from delete' -s h -l help -d 'help for delete'
complete -f -c gist -n __fish_use_subcommand -a edit -d 'Edit the gist file and sync after'
complete -c gist -n '__fish_seen_subcommand_from edit' -s h -l help -d 'help for edit'
complete -f -c gist -n __fish_use_subcommand -a new -d 'Create a new gist'
complete -c gist -n '__fish_seen_subcommand_from new' -s h -l help -d 'help for new'
complete -c gist -n '__fish_seen_subcommand_from new' -s o -l open -d 'Open with the default browser'
complete -c gist -n '__fish_seen_subcommand_from new' -s p -l private -d 'Create as private gist'
complete -f -c gist -n __fish_use_subcommand -a open -d Open\ user\'s\ gist
complete -c gist -n '__fish_seen_subcommand_from open' -s h -l help -d 'help for open'
complete -c gist -n '__fish_seen_subcommand_from open' -l no-select -d 'Open only gist base URL without selecting'
complete -c gist -n '__fish_seen_subcommand_from open' -s s -l starred -d 'Open your starred gist'
complete -f -c gist -n __fish_use_subcommand -a run -d 'Run the gist snippet as a script'
complete -c gist -n '__fish_seen_subcommand_from run' -s h -l help -d 'help for run'
complete -c gist -n '__fish_seen_subcommand_from run' -s s -l starred -d 'Open your starred gist'
complete -c gist -s c -l cache-clear -d 'clear cache'
complete -c gist -s h -l help -d 'help for gist'
complete -c gist -n __fish_no_arguments -s v -l version -d 'show the version and exit'
