complete -c gpg-agent -l daemon -d 'run in daemon mode (background)'
complete -c gpg-agent -l server -d 'run in server mode (foreground)'
complete -c gpg-agent -l supervised -d 'run in supervised mode'
complete -c gpg-agent -s v -l verbose -d verbose
complete -c gpg-agent -s q -l quiet -d 'be somewhat more quiet'
complete -c gpg-agent -s s -l sh -d 'sh-style command output'
complete -c gpg-agent -s c -l csh -d 'csh-style command output'
complete -c gpg-agent -l options -d 'FILE                  read options from FILE'
complete -c gpg-agent -l no-detach -d 'do not detach from the console'
complete -c gpg-agent -l log-file -d 'use a log file for the server'
complete -c gpg-agent -l pinentry-program -d 'PGM          use PGM as the PIN-Entry program'
complete -c gpg-agent -l scdaemon-program -d 'PGM          use PGM as the SCdaemon program'
complete -c gpg-agent -l disable-scdaemon -d 'do not use the SCdaemon'
complete -c gpg-agent -l extra-socket -d 'NAME             accept some commands via NAME'
complete -c gpg-agent -l keep-tty -d 'ignore requests to change the TTY'
complete -c gpg-agent -l keep-display -d 'ignore requests to change the X display'
complete -c gpg-agent -l default-cache-ttl -d 'N           expire cached PINs after N seconds'
complete -c gpg-agent -l ignore-cache-for-signing -d 'do not use the PIN cache when signing'
complete -c gpg-agent -l no-allow-external-cache -d 'disallow the use of an external password cache'
complete -c gpg-agent -l no-allow-mark-trusted -d 'disallow clients to mark keys as "trusted"'
complete -c gpg-agent -l allow-preset-passphrase -d 'allow presetting passphrase'
complete -c gpg-agent -l no-allow-loopback-pinentry -d 'disallow caller to override the pinentry'
complete -c gpg-agent -l allow-emacs-pinentry -d 'allow passphrase to be prompted through Emacs'
complete -c gpg-agent -l enable-ssh-support -d 'enable ssh support'
complete -c gpg-agent -l ssh-fingerprint-digest -d 'ALGO   use ALGO to show ssh fingerprints'
