complete -c HandBrakeCLI -s h -l help -d 'Print help'
complete -c HandBrakeCLI -n __fish_no_arguments -l version -d 'Print version'
complete -c HandBrakeCLI -l json -d 'Log title, progress, and version info in'
complete -c HandBrakeCLI -s z -l preset-list -d 'List available presets'
complete -c HandBrakeCLI -l preset-import-file -d '<filespec>'
complete -c HandBrakeCLI -l preset-import-gui -d 'Import presets from GUI config preset file.'
complete -c HandBrakeCLI -l preset-export -d '<string>'
complete -f -c HandBrakeCLI -n __fish_use_subcommand -a write -d 'a json representation of the preset to the'
complete -f -c HandBrakeCLI -n __fish_use_subcommand -a console -d or\ a\ file\ if\ \'--preset-export-file\'\ is
complete -c HandBrakeCLI -l preset-export-file -d '<filename>'
complete -c HandBrakeCLI -l preset-export-description -d '<string>'
complete -c HandBrakeCLI -l queue-import-file -d '<filename>'
complete -c HandBrakeCLI -l no-dvdnav -d 'Do not use dvdnav for reading DVDs'
complete -c HandBrakeCLI -s i -l input -d '<string>    Set input file or device ("source")'
complete -c HandBrakeCLI -s t -l title -d '<number>    Select a title to encode (0 to scan all titles'
complete -c HandBrakeCLI -l min-duration -d 'Set the minimum title duration (in seconds).'
complete -c HandBrakeCLI -l scan -d 'Scan selected title only.'
complete -c HandBrakeCLI -l main-feature -d 'Detect and select the main feature title.'
complete -c HandBrakeCLI -s c -l chapters -d '<string> Select chapters (e.g. "1-3" for chapters'
complete -c HandBrakeCLI -l angle -d '<number>    Select the video angle (DVD or Blu-ray only)'
complete -c HandBrakeCLI -l previews -d '<number:boolean>'
complete -c HandBrakeCLI -l start-at-preview -d '<number>'
complete -c HandBrakeCLI -l start-at -d '<string:number>'
complete -c HandBrakeCLI -l stop-at -d '<string:number>'
complete -c HandBrakeCLI -s o -l output -d '<filename> Set destination file name'
complete -c HandBrakeCLI -s f -l format -d '<string>   Select container format:'
complete -c HandBrakeCLI -s m -l markers -d 'Add chapter markers'
complete -c HandBrakeCLI -l no-markers -d 'Disable preset chapter markers'
complete -c HandBrakeCLI -s O -l optimize -d 'Optimize MP4 files for HTTP streaming (fast start,'
complete -c HandBrakeCLI -l no-optimize -d Disable\ preset\ \'optimize\'
complete -c HandBrakeCLI -s I -l ipod-atom -d 'Add iPod 5G compatibility atom to MP4 container'
complete -c HandBrakeCLI -l no-ipod-atom -d 'Disable iPod 5G atom'
complete -c HandBrakeCLI -l align-av -d 'Add audio silence or black video frames to start'
complete -c HandBrakeCLI -l inline-parameter-sets -d 'Create adaptive streaming compatible output.'
complete -c HandBrakeCLI -s e -l encoder -d '<string>  Select video encoder:'
complete -c HandBrakeCLI -l encoder-preset -d '<string>'
complete -c HandBrakeCLI -l encoder-preset-list -d '<string>'
complete -c HandBrakeCLI -l encoder-tune -d '<string>'
complete -c HandBrakeCLI -l encoder-tune-list -d '<string>'
complete -c HandBrakeCLI -s x -l encopts -d '<string>  Specify advanced encoding options in the same'
complete -c HandBrakeCLI -l encoder-profile -d '<string>'
complete -c HandBrakeCLI -l encoder-profile-list -d '<string>'
complete -c HandBrakeCLI -l encoder-level -d '<string>'
complete -c HandBrakeCLI -l encoder-level-list -d '<string>'
complete -c HandBrakeCLI -s q -l quality -d '<float>   Set video quality (e.g. 22.0)'
complete -c HandBrakeCLI -s b -l vb -d '<number>       Set video bitrate in kbit/s (default: 1000)'
complete -c HandBrakeCLI -s 2 -l two-pass -d 'Use two-pass mode'
complete -c HandBrakeCLI -l no-two-pass -d 'Disable two-pass mode'
complete -c HandBrakeCLI -s T -l turbo -d 'When using 2-pass use "turbo" options on the'
complete -c HandBrakeCLI -l no-turbo -d Disable\ 2-pass\ mode\'s\ \"turbo\"\ first\ pass
complete -c HandBrakeCLI -s r -l rate -d '<float>      Set video framerate'
complete -c HandBrakeCLI -l audio-lang-list -d '<string>'
complete -c HandBrakeCLI -l all-audio -d 'Select all audio tracks matching languages in'
complete -c HandBrakeCLI -l first-audio -d 'Select first audio track matching languages in'
complete -c HandBrakeCLI -s a -l audio -d '<string>    Select audio track(s), separated by commas'
complete -c HandBrakeCLI -s E -l aencoder -d '<string> Select audio encoder(s):'
complete -c HandBrakeCLI -l audio-copy-mask -d '<string>'
complete -c HandBrakeCLI -l audio-fallback -d '<string>'
complete -c HandBrakeCLI -s B -l ab -d '<number>       Set audio track bitrate(s) in kbit/s.'
complete -c HandBrakeCLI -s Q -l aq -d '<float>        Set audio quality metric.'
complete -c HandBrakeCLI -s C -l ac -d '<float>        Set audio compression metric.'
complete -c HandBrakeCLI -s 6 -l mixdown -d '<string>  Format(s) for audio downmixing/upmixing:'
complete -c HandBrakeCLI -l normalize-mix -d 'Normalize audio mix levels to prevent clipping.'
complete -c HandBrakeCLI -s R -l arate -d 'Set audio samplerate(s)'
complete -c HandBrakeCLI -s D -l drc -d '<float>       Apply extra dynamic range compression to the'
complete -c HandBrakeCLI -l gain -d '<float>      Amplify or attenuate audio before encoding.  Does'
complete -c HandBrakeCLI -l adither -d '<string>  Select dithering to apply before encoding audio:'
complete -c HandBrakeCLI -s A -l aname -d '<string>    Set audio track name(s).'
complete -c HandBrakeCLI -s w -l width -d '<number>   Set storage width in pixels'
complete -c HandBrakeCLI -s l -l height -d '<number>   Set storage height in pixels'
complete -c HandBrakeCLI -l crop -d '<top:bottom:left:right>'
complete -c HandBrakeCLI -l loose-crop -d 'Always crop to a multiple of the modulus'
complete -c HandBrakeCLI -l no-loose-crop -d Disable\ preset\ \'loose-crop\'
complete -c HandBrakeCLI -s Y -l maxHeight -d '<number>'
complete -c HandBrakeCLI -s X -l maxWidth -d '<number>'
complete -c HandBrakeCLI -l non-anamorphic -d 'Set pixel aspect ratio to 1:1'
complete -c HandBrakeCLI -l auto-anamorphic -d 'Store pixel aspect ratio that maximizes storage'
complete -c HandBrakeCLI -l loose-anamorphic -d 'Store pixel aspect ratio that is as close as'
complete -c HandBrakeCLI -l custom-anamorphic -d 'Store pixel aspect ratio in video stream and'
complete -c HandBrakeCLI -l display-width -d '<number>'
complete -c HandBrakeCLI -l keep-display-aspect -d Preserve\ the\ source\'s\ display\ aspect\ ratio
complete -c HandBrakeCLI -l pixel-aspect -d '<par_x:par_y>'
complete -c HandBrakeCLI -l itu-par -d 'Use wider ITU pixel aspect values for loose and'
complete -c HandBrakeCLI -l no-itu-par -d Disable\ preset\ \'itu-par\'
complete -c HandBrakeCLI -l modulus -d '<number>      Set storage width and height modulus'
complete -c HandBrakeCLI -s M -l color-matrix -d '<string>'
complete -c HandBrakeCLI -l no-comb-detect -d 'Disable preset comb-detect filter'
complete -c HandBrakeCLI -l no-deinterlace -d 'Disable preset deinterlace filter'
complete -c HandBrakeCLI -l no-decomb -d 'Disable preset decomb filter'
complete -c HandBrakeCLI -l no-detelecine -d 'Disable preset detelecine filter'
complete -c HandBrakeCLI -l no-hqdn3d -d 'Disable preset hqdn3d filter'
complete -c HandBrakeCLI -l no-nlmeans -d 'Disable preset NLMeans filter'
complete -c HandBrakeCLI -l nlmeans-tune -d '<string> Tune NLMeans filter to content type'
complete -c HandBrakeCLI -l no-unsharp -d 'Disable preset unsharp filter'
complete -c HandBrakeCLI -l unsharp-tune -d '<string> Tune unsharp filter'
complete -c HandBrakeCLI -l no-lapsharp -d 'Disable preset lapsharp filter'
complete -c HandBrakeCLI -l lapsharp-tune -d '<string>'
complete -c HandBrakeCLI -l no-deblock -d 'Disable preset deblock filter'
complete -c HandBrakeCLI -l pad -d '<string>          Pad image with borders (e.g. letterbox).'
complete -c HandBrakeCLI -s g -l grayscale -d 'Grayscale encoding'
complete -c HandBrakeCLI -l no-grayscale -d Disable\ preset\ \'grayscale\'
complete -c HandBrakeCLI -l subtitle-lang-list -d '<string>'
complete -c HandBrakeCLI -l all-subtitles -d 'Select all subtitle tracks matching languages in'
complete -c HandBrakeCLI -l first-subtitle -d 'Select first subtitle track matching languages in'
complete -c HandBrakeCLI -s s -l subtitle -d '<string>  Select subtitle track(s), separated by commas'
complete -c HandBrakeCLI -s N -l native-language -d '<string>'
complete -c HandBrakeCLI -l native-dub -d 'Used in conjunction with --native-language'
complete -c HandBrakeCLI -l srt-file -d '<string>   SubRip SRT filename(s), separated by commas.'
complete -c HandBrakeCLI -l srt-codeset -d '<string>'
complete -f -c HandBrakeCLI -n __fish_use_subcommand -a --srt-offset -d '<string> Offset (in milliseconds) to apply to the SRT'
complete -c HandBrakeCLI -l srt-lang -d '<string>   SRT track language as an ISO 639-2 code'
