complete -f -c ipa -n __fish_use_subcommand -a build -d 'Create a new .ipa file for your app'
complete -c ipa -n '__fish_seen_subcommand_from build' -s w -l workspace -d 'WORKSPACE Workspace (.xcworkspace) file to use to build app (automatically detected in current directory)'
complete -c ipa -n '__fish_seen_subcommand_from build' -s p -l project -d 'PROJECT Project (.xcodeproj) file to use to build app (automatically detected in current directory, overridden by --workspace option, if passed)'
complete -c ipa -n '__fish_seen_subcommand_from build' -s c -l configuration -d 'CONFIGURATION Configuration used to build'
complete -c ipa -n '__fish_seen_subcommand_from build' -s s -l scheme -d 'SCHEME  Scheme used to build app'
complete -c ipa -n '__fish_seen_subcommand_from build' -l xcconfig -d 'XCCONFIG  use an extra XCCONFIG file to build the app'
complete -c ipa -n '__fish_seen_subcommand_from build' -l xcargs -d 'XCARGS      pass additional arguments to xcodebuild when building the app. Be sure to quote multiple args.'
complete -c ipa -n '__fish_seen_subcommand_from build' -s d -l destination -d 'DESTINATION Destination. Defaults to current directory'
complete -c ipa -n '__fish_seen_subcommand_from build' -s m -l embed -d 'PROVISION Sign .ipa file with .mobileprovision'
complete -c ipa -n '__fish_seen_subcommand_from build' -s i -l identity -d 'IDENTITY Identity to be used along with --embed'
complete -c ipa -n '__fish_seen_subcommand_from build' -l sdk -d 'SDK            use SDK as the name or path of the base SDK when building the project'
complete -c ipa -n '__fish_seen_subcommand_from build' -l ipa -d 'IPA            specify the name of the .ipa file to generate (including file extension)'
complete -c ipa -l verbose
complete -c ipa -s h -l help -d 'Display help documentation'
complete -c ipa -n __fish_no_arguments -s v -l version -d 'Display version information'
complete -c ipa -s t -l trace -d 'Display backtrace when an error occurs'
