complete -c lsd -s a -l all -d 'Do not ignore entries starting with .'
complete -c lsd -s A -l almost-all -d 'Do not list implied . and ..'
complete -c lsd -l classic -d 'Enable classic mode (no colors or icons)'
complete -c lsd -s d -l directory-only -d 'Display directories themselves, and not their contents'
complete -c lsd -l help -d 'Prints help information'
complete -c lsd -s h -l human-readable -d 'For ls compatibility purposes ONLY, currently set by default'
complete -c lsd -s F -l classify -d 'Append indicator (one of */=>@|) at the end of the file names'
complete -c lsd -s l -l long -d 'Display extended file metadata as a table'
complete -c lsd -l no-symlink -d 'Do not display symlink target'
complete -c lsd -s 1 -l oneline -d 'Display one entry per line'
complete -c lsd -s R -l recursive -d 'Recurse into directories'
complete -c lsd -s r -l reverse -d 'Reverse the order of the sort'
complete -c lsd -s S -l sizesort -d 'Sort by size'
complete -c lsd -s t -l timesort -d 'Sort by time modified'
complete -c lsd -l total-size -d 'Display the total size of directories'
complete -c lsd -l tree -d 'Recurse into directories and present the result as a tree'
complete -c lsd -n __fish_no_arguments -s V -l version -d 'Prints version information'
complete -c lsd -l blocks -d '<blocks>...            Specify the blocks that will be displayed and in what order [default: permission,user,group,size,date,name]  [possible values: permission, user, group, size, date, name]'
complete -c lsd -l color -d '<color>...              When to use terminal colours [default: auto]  [possible values: always, auto, never]'
complete -c lsd -l date -d '<date>...                How to display date [default: date]  [possible values: date, relative]'
complete -c lsd -l depth -d '<num>                   Stop recursing into directories after reaching specified depth'
complete -c lsd -l group-dirs -d '<group-dirs>...    Sort the directories then the files [default: none]  [possible values: none, first, last]'
complete -c lsd -l icon -d '<icon>...                When to print the icons [default: auto]  [possible values: always, auto, never]'
complete -c lsd -l icon-theme -d '<icon-theme>...    Whether to use fancy or unicode icons [default: fancy]  [possible values: fancy, unicode]'
complete -c lsd -l size -d '<size>...                How to display size [default: default]  [possible values: default, short, bytes]'
