complete -c multipass -s h -l help -d 'Display this help'
complete -c multipass -s v -l verbose -d 'Increase logging verbosity, repeat up to three times for more'
complete -f -c multipass -n __fish_use_subcommand -a delete -d 'Delete instances'
complete -c multipass -n '__fish_seen_subcommand_from delete' -s h -l help -d 'Display this help'
complete -c multipass -n '__fish_seen_subcommand_from delete' -s v -l verbose -d 'Increase logging verbosity, repeat up to three times for more'
complete -c multipass -n '__fish_seen_subcommand_from delete' -l all -d 'Delete all instances'
complete -c multipass -n '__fish_seen_subcommand_from delete' -s p -l purge -d 'Purge instances immediately'
complete -f -c multipass -n __fish_use_subcommand -a find -d 'Display available images to create instances from'
complete -c multipass -n '__fish_seen_subcommand_from find' -s h -l help -d 'Display this help'
complete -c multipass -n '__fish_seen_subcommand_from find' -s v -l verbose -d 'Increase logging verbosity, repeat up to three times for'
complete -c multipass -n '__fish_seen_subcommand_from find' -l show-unsupported -d 'Show unsupported cloud images as well'
complete -c multipass -n '__fish_seen_subcommand_from find' -l format -d '<format>   Output list in the requested format.'
complete -f -c multipass -n __fish_use_subcommand -a get -d 'Get a configuration option'
complete -c multipass -n '__fish_seen_subcommand_from get' -s h -l help -d 'Display this help'
complete -c multipass -n '__fish_seen_subcommand_from get' -s v -l verbose -d 'Increase logging verbosity, repeat up to three times for more'
complete -f -c multipass -n __fish_use_subcommand -a info -d 'Display information about instances'
complete -c multipass -n '__fish_seen_subcommand_from info' -s h -l help -d 'Display this help'
complete -c multipass -n '__fish_seen_subcommand_from info' -s v -l verbose -d 'Increase logging verbosity, repeat up to three times for'
complete -c multipass -n '__fish_seen_subcommand_from info' -l all -d 'Display info for all instances'
complete -c multipass -n '__fish_seen_subcommand_from info' -l format -d '<format>  Output info in the requested format.'
complete -f -c multipass -n __fish_use_subcommand -a launch -d 'Create and start an Ubuntu instance'
complete -c multipass -n '__fish_seen_subcommand_from launch' -s h -l help -d 'Display this help'
complete -c multipass -n '__fish_seen_subcommand_from launch' -s v -l verbose -d 'Increase logging verbosity, repeat up to three times for'
complete -c multipass -n '__fish_seen_subcommand_from launch' -s c -l cpus -d '<cpus>    Number of CPUs to allocate'
complete -c multipass -n '__fish_seen_subcommand_from launch' -s d -l disk -d '<disk>    Disk space to allocate. Positive integers, in bytes, or'
complete -c multipass -n '__fish_seen_subcommand_from launch' -s m -l mem -d '<mem>      Amount of memory to allocate. Positive integers, in'
complete -c multipass -n '__fish_seen_subcommand_from launch' -s n -l name -d '<name>    Name for the instance'
complete -c multipass -n '__fish_seen_subcommand_from launch' -l cloud-init -d \<file\>\ \ Path\ to\ a\ user-data\ cloud-init\ configuration,\ or\ \'-\'\ for
complete -f -c multipass -n __fish_use_subcommand -a list -d 'List all available instances'
complete -c multipass -n '__fish_seen_subcommand_from list' -s h -l help -d 'Display this help'
complete -c multipass -n '__fish_seen_subcommand_from list' -s v -l verbose -d 'Increase logging verbosity, repeat up to three times for'
complete -c multipass -n '__fish_seen_subcommand_from list' -l format -d '<format>  Output list in the requested format.'
complete -f -c multipass -n __fish_use_subcommand -a mount -d 'Mount a local directory in the instance'
complete -c multipass -n '__fish_seen_subcommand_from mount' -s h -l help -d 'Display this help'
complete -c multipass -n '__fish_seen_subcommand_from mount' -s v -l verbose -d 'Increase logging verbosity, repeat up to'
complete -c multipass -n '__fish_seen_subcommand_from mount' -s g -l gid-map -d '<host>:<instance>  A mapping of group IDs for use in the mount.'
complete -c multipass -n '__fish_seen_subcommand_from mount' -s u -l uid-map -d '<host>:<instance>  A mapping of user IDs for use in the mount.'
complete -f -c multipass -n __fish_use_subcommand -a purge -d 'Purge all deleted instances permanently'
complete -c multipass -n '__fish_seen_subcommand_from purge' -s h -l help -d 'Display this help'
complete -c multipass -n '__fish_seen_subcommand_from purge' -s v -l verbose -d 'Increase logging verbosity, repeat up to three times for more'
complete -f -c multipass -n __fish_use_subcommand -a recover -d 'Recover deleted instances'
complete -c multipass -n '__fish_seen_subcommand_from recover' -s h -l help -d 'Display this help'
complete -c multipass -n '__fish_seen_subcommand_from recover' -s v -l verbose -d 'Increase logging verbosity, repeat up to three times for more'
complete -c multipass -n '__fish_seen_subcommand_from recover' -l all -d 'Recover all deleted instances'
complete -f -c multipass -n __fish_use_subcommand -a restart -d 'Restart instances'
complete -c multipass -n '__fish_seen_subcommand_from restart' -s h -l help -d 'Display this help'
complete -c multipass -n '__fish_seen_subcommand_from restart' -s v -l verbose -d 'Increase logging verbosity, repeat up to three times for more'
complete -c multipass -n '__fish_seen_subcommand_from restart' -l all -d 'Restart all instances'
complete -c multipass -n '__fish_seen_subcommand_from restart' -l all -d option,\ \'primary\'\ will\ be\ assumed.
complete -f -c multipass -n __fish_use_subcommand -a set -d 'Set a configuration option'
complete -c multipass -n '__fish_seen_subcommand_from set' -s h -l help -d 'Display this help'
complete -c multipass -n '__fish_seen_subcommand_from set' -s v -l verbose -d 'Increase logging verbosity, repeat up to three times for more'
complete -f -c multipass -n __fish_use_subcommand -a shell -d 'Open a shell on a running instance'
complete -c multipass -n '__fish_seen_subcommand_from shell' -s h -l help -d 'Display this help'
complete -c multipass -n '__fish_seen_subcommand_from shell' -s v -l verbose -d 'Increase logging verbosity, repeat up to three times for more'
complete -f -c multipass -n __fish_use_subcommand -a start -d 'Start instances'
complete -c multipass -n '__fish_seen_subcommand_from start' -s h -l help -d 'Display this help'
complete -c multipass -n '__fish_seen_subcommand_from start' -s v -l verbose -d 'Increase logging verbosity, repeat up to three times for more'
complete -c multipass -n '__fish_seen_subcommand_from start' -l all -d 'Start all instances'
complete -f -c multipass -n __fish_use_subcommand -a stop -d 'Stop running instances'
complete -c multipass -n '__fish_seen_subcommand_from stop' -s h -l help -d 'Display this help'
complete -c multipass -n '__fish_seen_subcommand_from stop' -s v -l verbose -d 'Increase logging verbosity, repeat up to three times for'
complete -c multipass -n '__fish_seen_subcommand_from stop' -l all -d 'Stop all instances'
complete -c multipass -n '__fish_seen_subcommand_from stop' -s t -l time -d '<time>  Time from now, in minutes, to delay shutdown of the'
complete -c multipass -n '__fish_seen_subcommand_from stop' -s c -l cancel -d 'Cancel a pending delayed shutdown'
complete -c multipass -n '__fish_seen_subcommand_from stop' -l all -d option,\ \'primary\'\ will\ be\ assumed
complete -f -c multipass -n __fish_use_subcommand -a suspend -d 'Suspend running instances'
complete -c multipass -n '__fish_seen_subcommand_from suspend' -s h -l help -d 'Display this help'
complete -c multipass -n '__fish_seen_subcommand_from suspend' -s v -l verbose -d 'Increase logging verbosity, repeat up to three times for more'
complete -c multipass -n '__fish_seen_subcommand_from suspend' -l all -d 'Suspend all instances'
complete -c multipass -n '__fish_seen_subcommand_from suspend' -l all -d option,\ \'primary\'\ will\ be\ assumed.
complete -f -c multipass -n __fish_use_subcommand -a transfer -d 'Transfer files between the host and instances'
complete -c multipass -n '__fish_seen_subcommand_from transfer' -s h -l help -d 'Display this help'
complete -c multipass -n '__fish_seen_subcommand_from transfer' -s v -l verbose -d 'Increase logging verbosity, repeat up to three times for more'
complete -f -c multipass -n __fish_use_subcommand -a umount -d 'Unmount a directory from an instance'
complete -c multipass -n '__fish_seen_subcommand_from umount' -s h -l help -d 'Display this help'
complete -c multipass -n '__fish_seen_subcommand_from umount' -s v -l verbose -d 'Increase logging verbosity, repeat up to three times for more'
complete -f -c multipass -n __fish_use_subcommand -a version -d 'Show version details'
complete -c multipass -n '__fish_seen_subcommand_from version' -s h -l help -d 'Display this help'
complete -c multipass -n '__fish_seen_subcommand_from version' -s v -l verbose -d 'Increase logging verbosity, repeat up to three times for more'
