complete -c procs -s a -l and -d 'AND  logic for multi-keyword'
complete -c procs -s o -l or -d 'OR   logic for multi-keyword'
complete -c procs -s d -l nand -d 'NAND logic for multi-keyword'
complete -c procs -s r -l nor -d 'NOR  logic for multi-keyword'
complete -c procs -s l -l list -d 'Show list of kind'
complete -c procs -s t -l tree -d 'Tree view'
complete -c procs -l config -d 'Generate configuration sample file'
complete -c procs -l suid -d 'Set suid bit and change binary owner to root'
complete -c procs -s h -l help -d 'Prints help information'
complete -c procs -n __fish_no_arguments -s V -l version -d 'Prints version information'
complete -c procs -s w -l watch -d '<second>         Watch mode'
complete -c procs -s i -l insert -d '<kind>...       Insert column to slot'
complete -c procs -l sorta -d '<kind>           Sort column by ascending'
complete -c procs -l sortd -d '<kind>           Sort column by descending'
complete -c procs -s c -l color -d '<color>          Color mode [possible values: auto, always, disable]'
complete -c procs -s p -l pager -d '<pager>          Pager mode [possible values: auto, always, disable]'
complete -c procs -l interval -d '<millisec>    Interval to calculate throughput [default: 100]'
