complete -f -c safe -n __fish_use_subcommand -a version -d 'Print the version of the safe CLI'
complete -f -c safe -n __fish_use_subcommand -a versions -d 'Print information about the versions of one or more paths'
complete -f -c safe -n __fish_use_subcommand -a x509 -d 'Issue / Revoke X.509 Certificates and Certificate Authorities'
complete -f -c safe -n __fish_use_subcommand -a x509 -d 'crl    Manage a X.509 Certificate Authority Revocation List'
complete -f -c safe -n __fish_use_subcommand -a x509 -d 'issue  Issue X.509 Certificates and Certificate Authorities'
complete -f -c safe -n __fish_use_subcommand -a x509 -d 'reissue  Reissue X.509 Certificates and Certificate Authorities'
complete -f -c safe -n __fish_use_subcommand -a x509 -d 'renew  Renew X.509 Certificates and Certificate Authorities'
complete -f -c safe -n __fish_use_subcommand -a x509 -d 'revoke  Revoke X.509 Certificates and Certificate Authorities'
complete -f -c safe -n __fish_use_subcommand -a x509 -d 'show   Show the details of an X.509 Certificate'
complete -f -c safe -n __fish_use_subcommand -a x509 -d 'validate  Validate an X.509 Certificate / Private Key'
