complete -c tb -s a -l archive -d 'Display archived items'
complete -c tb -s b -l begin -d 'Start/pause task'
complete -c tb -s c -l check -d 'Check/uncheck task'
complete -c tb -l clear -d 'Delete all checked items'
complete -c tb -s y -l copy -d 'Copy item description'
complete -c tb -s d -l delete -d 'Delete item'
complete -c tb -s e -l edit -d 'Edit item description'
complete -c tb -s f -l find -d 'Search for items'
complete -c tb -s h -l help -d 'Display help message'
complete -c tb -s l -l list -d 'List items by attributes'
complete -c tb -s m -l move -d 'Move item between boards'
complete -c tb -s n -l note -d 'Create note'
complete -c tb -s p -l priority -d 'Update priority of task'
complete -c tb -s r -l restore -d 'Restore items from archive'
complete -c tb -s s -l star -d 'Star/unstar item'
complete -c tb -s t -l task -d 'Create task'
complete -c tb -s i -l timeline -d 'Display timeline view'
complete -c tb -n __fish_no_arguments -s v -l version -d 'Display installed version'
