complete -f -c td -n __fish_use_subcommand -a init -d 'Initialize a collection of todos'
complete -f -c td -n __fish_use_subcommand -a add -d 'Add a new todo'
complete -f -c td -n __fish_use_subcommand -a modify -d 'Modify the text of an existing todo'
complete -f -c td -n __fish_use_subcommand -a toggle -d 'Toggle the status of a todo by giving his id'
complete -f -c td -n __fish_use_subcommand -a clean -d 'Remove finished todos from the list'
complete -f -c td -n __fish_use_subcommand -a reorder -d 'Reset ids of todo (no arguments) or swap the position of two todos'
complete -f -c td -n __fish_use_subcommand -a search -d 'Search a string in all todos'
complete -f -c td -n __fish_use_subcommand -a help -d 'Shows a list of commands or help for one command'
complete -c td -s d -l done -d 'print done todos'
complete -c td -s a -l all -d 'print all todos'
complete -c td -s h -l help -d 'show help'
complete -c td -n __fish_no_arguments -s v -l version -d 'print the version'
