complete -c teems-rust -s h -l help -d 'Prints help information'
complete -c teems-rust -n __fish_no_arguments -s V -l version -d 'Prints version information'
complete -c teems-rust -s c -l config -d '<FILE>    a required json file containing the themes'
complete -f -c teems-rust -n __fish_use_subcommand -a activate -d 'Activate a theme'
complete -c teems-rust -n '__fish_seen_subcommand_from activate' -s h -l help -d 'Prints help information'
complete -c teems-rust -n __fish_no_arguments -s V -l version -d 'Prints version information'
complete -c teems-rust -n '__fish_seen_subcommand_from activate' -s t -l theme -d '<THEME>    a required name of a theme'
complete -f -c teems-rust -n __fish_use_subcommand -a list -d 'List all themes'
complete -c teems-rust -n '__fish_seen_subcommand_from list' -s h -l help -d 'Prints help information'
complete -c teems-rust -n __fish_no_arguments -s V -l version -d 'Prints version information'
