complete -f -c wuzz -n __fish_use_subcommand -a -c -d '--config PATH        Specify custom configuration file'
complete -f -c wuzz -n __fish_use_subcommand -a -e -d '--editor EDITOR      Specify external editor command'
complete -c wuzz -n '__fish_seen_subcommand_from -e' -s c -l config -d 'PATH        Specify custom configuration file'
complete -c wuzz -n '__fish_seen_subcommand_from -e' -s e -l editor -d 'EDITOR      Specify external editor command'
complete -c wuzz -n '__fish_seen_subcommand_from -e' -s f -l file -d 'REQUEST       Load a previous request'
complete -c wuzz -n '__fish_seen_subcommand_from -e' -s F -l form -d 'DATA          Add multipart form request data and set related request headers'
complete -c wuzz -n '__fish_seen_subcommand_from -e' -s h -l help -d 'Show this'
complete -c wuzz -n '__fish_seen_subcommand_from -e' -s j -l json -d 'JSON          Add JSON request data and set related request headers'
complete -c wuzz -n '__fish_seen_subcommand_from -e' -s k -l insecure -d 'Allow insecure SSL certs'
complete -c wuzz -n '__fish_seen_subcommand_from -e' -s R -l disable-redirects -d 'Do not follow HTTP redirects'
complete -c wuzz -n '__fish_seen_subcommand_from -e' -s T -l tls -d 'MIN,MAX        Restrict allowed TLS versions (values: SSL3.0,TLS1.0,TLS1.1,TLS1.2)'
complete -c wuzz -n '__fish_seen_subcommand_from -e' -s 1 -l tlsv1 -d 'Forces TLS version 1.x (1.0, 1.1 or 1.2)'
complete -c wuzz -n __fish_no_arguments -s v -l version -d 'Display version number'
complete -c wuzz -n '__fish_seen_subcommand_from -e' -s x -l proxy -d 'URL          Set HTTP(S) or SOCKS5 proxy'
complete -f -c wuzz -n __fish_use_subcommand -a -f -d '--file REQUEST       Load a previous request'
complete -c wuzz -n '__fish_seen_subcommand_from -f' -s c -l config -d 'PATH        Specify custom configuration file'
complete -c wuzz -n '__fish_seen_subcommand_from -f' -s e -l editor -d 'EDITOR      Specify external editor command'
complete -c wuzz -n '__fish_seen_subcommand_from -f' -s f -l file -d 'REQUEST       Load a previous request'
complete -c wuzz -n '__fish_seen_subcommand_from -f' -s F -l form -d 'DATA          Add multipart form request data and set related request headers'
complete -c wuzz -n '__fish_seen_subcommand_from -f' -s h -l help -d 'Show this'
complete -c wuzz -n '__fish_seen_subcommand_from -f' -s j -l json -d 'JSON          Add JSON request data and set related request headers'
complete -c wuzz -n '__fish_seen_subcommand_from -f' -s k -l insecure -d 'Allow insecure SSL certs'
complete -c wuzz -n '__fish_seen_subcommand_from -f' -s R -l disable-redirects -d 'Do not follow HTTP redirects'
complete -c wuzz -n '__fish_seen_subcommand_from -f' -s T -l tls -d 'MIN,MAX        Restrict allowed TLS versions (values: SSL3.0,TLS1.0,TLS1.1,TLS1.2)'
complete -c wuzz -n '__fish_seen_subcommand_from -f' -s 1 -l tlsv1 -d 'Forces TLS version 1.x (1.0, 1.1 or 1.2)'
complete -c wuzz -n __fish_no_arguments -s v -l version -d 'Display version number'
complete -c wuzz -n '__fish_seen_subcommand_from -f' -s x -l proxy -d 'URL          Set HTTP(S) or SOCKS5 proxy'
complete -f -c wuzz -n __fish_use_subcommand -a -F -d '--form DATA          Add multipart form request data and set related request headers'
complete -c wuzz -n '__fish_seen_subcommand_from -F' -s c -l config -d 'PATH        Specify custom configuration file'
complete -c wuzz -n '__fish_seen_subcommand_from -F' -s e -l editor -d 'EDITOR      Specify external editor command'
complete -c wuzz -n '__fish_seen_subcommand_from -F' -s f -l file -d 'REQUEST       Load a previous request'
complete -c wuzz -n '__fish_seen_subcommand_from -F' -s F -l form -d 'DATA          Add multipart form request data and set related request headers'
complete -c wuzz -n '__fish_seen_subcommand_from -F' -s h -l help -d 'Show this'
complete -c wuzz -n '__fish_seen_subcommand_from -F' -s j -l json -d 'JSON          Add JSON request data and set related request headers'
complete -c wuzz -n '__fish_seen_subcommand_from -F' -s k -l insecure -d 'Allow insecure SSL certs'
complete -c wuzz -n '__fish_seen_subcommand_from -F' -s R -l disable-redirects -d 'Do not follow HTTP redirects'
complete -c wuzz -n '__fish_seen_subcommand_from -F' -s T -l tls -d 'MIN,MAX        Restrict allowed TLS versions (values: SSL3.0,TLS1.0,TLS1.1,TLS1.2)'
complete -c wuzz -n '__fish_seen_subcommand_from -F' -s 1 -l tlsv1 -d 'Forces TLS version 1.x (1.0, 1.1 or 1.2)'
complete -c wuzz -n __fish_no_arguments -s v -l version -d 'Display version number'
complete -c wuzz -n '__fish_seen_subcommand_from -F' -s x -l proxy -d 'URL          Set HTTP(S) or SOCKS5 proxy'
complete -f -c wuzz -n __fish_use_subcommand -a If -d 'the value starts with @ it will be handled as a file path for upload'
complete -c wuzz -n '__fish_seen_subcommand_from If' -s c -l config -d 'PATH        Specify custom configuration file'
complete -c wuzz -n '__fish_seen_subcommand_from If' -s e -l editor -d 'EDITOR      Specify external editor command'
complete -c wuzz -n '__fish_seen_subcommand_from If' -s f -l file -d 'REQUEST       Load a previous request'
complete -c wuzz -n '__fish_seen_subcommand_from If' -s F -l form -d 'DATA          Add multipart form request data and set related request headers'
complete -c wuzz -n '__fish_seen_subcommand_from If' -s h -l help -d 'Show this'
complete -c wuzz -n '__fish_seen_subcommand_from If' -s j -l json -d 'JSON          Add JSON request data and set related request headers'
complete -c wuzz -n '__fish_seen_subcommand_from If' -s k -l insecure -d 'Allow insecure SSL certs'
complete -c wuzz -n '__fish_seen_subcommand_from If' -s R -l disable-redirects -d 'Do not follow HTTP redirects'
complete -c wuzz -n '__fish_seen_subcommand_from If' -s T -l tls -d 'MIN,MAX        Restrict allowed TLS versions (values: SSL3.0,TLS1.0,TLS1.1,TLS1.2)'
complete -c wuzz -n '__fish_seen_subcommand_from If' -s 1 -l tlsv1 -d 'Forces TLS version 1.x (1.0, 1.1 or 1.2)'
complete -c wuzz -n __fish_no_arguments -s v -l version -d 'Display version number'
complete -c wuzz -n '__fish_seen_subcommand_from If' -s x -l proxy -d 'URL          Set HTTP(S) or SOCKS5 proxy'
complete -f -c wuzz -n __fish_use_subcommand -a -h -d '--help               Show this'
complete -c wuzz -n '__fish_seen_subcommand_from -h' -s c -l config -d 'PATH        Specify custom configuration file'
complete -c wuzz -n '__fish_seen_subcommand_from -h' -s e -l editor -d 'EDITOR      Specify external editor command'
complete -c wuzz -n '__fish_seen_subcommand_from -h' -s f -l file -d 'REQUEST       Load a previous request'
complete -c wuzz -n '__fish_seen_subcommand_from -h' -s F -l form -d 'DATA          Add multipart form request data and set related request headers'
complete -c wuzz -n '__fish_seen_subcommand_from -h' -s h -l help -d 'Show this'
complete -c wuzz -n '__fish_seen_subcommand_from -h' -s j -l json -d 'JSON          Add JSON request data and set related request headers'
complete -c wuzz -n '__fish_seen_subcommand_from -h' -s k -l insecure -d 'Allow insecure SSL certs'
complete -c wuzz -n '__fish_seen_subcommand_from -h' -s R -l disable-redirects -d 'Do not follow HTTP redirects'
complete -c wuzz -n '__fish_seen_subcommand_from -h' -s T -l tls -d 'MIN,MAX        Restrict allowed TLS versions (values: SSL3.0,TLS1.0,TLS1.1,TLS1.2)'
complete -c wuzz -n '__fish_seen_subcommand_from -h' -s 1 -l tlsv1 -d 'Forces TLS version 1.x (1.0, 1.1 or 1.2)'
complete -c wuzz -n __fish_no_arguments -s v -l version -d 'Display version number'
complete -c wuzz -n '__fish_seen_subcommand_from -h' -s x -l proxy -d 'URL          Set HTTP(S) or SOCKS5 proxy'
complete -f -c wuzz -n __fish_use_subcommand -a -j -d '--json JSON          Add JSON request data and set related request headers'
complete -c wuzz -n '__fish_seen_subcommand_from -j' -s c -l config -d 'PATH        Specify custom configuration file'
complete -c wuzz -n '__fish_seen_subcommand_from -j' -s e -l editor -d 'EDITOR      Specify external editor command'
complete -c wuzz -n '__fish_seen_subcommand_from -j' -s f -l file -d 'REQUEST       Load a previous request'
complete -c wuzz -n '__fish_seen_subcommand_from -j' -s F -l form -d 'DATA          Add multipart form request data and set related request headers'
complete -c wuzz -n '__fish_seen_subcommand_from -j' -s h -l help -d 'Show this'
complete -c wuzz -n '__fish_seen_subcommand_from -j' -s j -l json -d 'JSON          Add JSON request data and set related request headers'
complete -c wuzz -n '__fish_seen_subcommand_from -j' -s k -l insecure -d 'Allow insecure SSL certs'
complete -c wuzz -n '__fish_seen_subcommand_from -j' -s R -l disable-redirects -d 'Do not follow HTTP redirects'
complete -c wuzz -n '__fish_seen_subcommand_from -j' -s T -l tls -d 'MIN,MAX        Restrict allowed TLS versions (values: SSL3.0,TLS1.0,TLS1.1,TLS1.2)'
complete -c wuzz -n '__fish_seen_subcommand_from -j' -s 1 -l tlsv1 -d 'Forces TLS version 1.x (1.0, 1.1 or 1.2)'
complete -c wuzz -n __fish_no_arguments -s v -l version -d 'Display version number'
complete -c wuzz -n '__fish_seen_subcommand_from -j' -s x -l proxy -d 'URL          Set HTTP(S) or SOCKS5 proxy'
complete -f -c wuzz -n __fish_use_subcommand -a -k -d '--insecure           Allow insecure SSL certs'
complete -c wuzz -n '__fish_seen_subcommand_from -k' -s c -l config -d 'PATH        Specify custom configuration file'
complete -c wuzz -n '__fish_seen_subcommand_from -k' -s e -l editor -d 'EDITOR      Specify external editor command'
complete -c wuzz -n '__fish_seen_subcommand_from -k' -s f -l file -d 'REQUEST       Load a previous request'
complete -c wuzz -n '__fish_seen_subcommand_from -k' -s F -l form -d 'DATA          Add multipart form request data and set related request headers'
complete -c wuzz -n '__fish_seen_subcommand_from -k' -s h -l help -d 'Show this'
complete -c wuzz -n '__fish_seen_subcommand_from -k' -s j -l json -d 'JSON          Add JSON request data and set related request headers'
complete -c wuzz -n '__fish_seen_subcommand_from -k' -s k -l insecure -d 'Allow insecure SSL certs'
complete -c wuzz -n '__fish_seen_subcommand_from -k' -s R -l disable-redirects -d 'Do not follow HTTP redirects'
complete -c wuzz -n '__fish_seen_subcommand_from -k' -s T -l tls -d 'MIN,MAX        Restrict allowed TLS versions (values: SSL3.0,TLS1.0,TLS1.1,TLS1.2)'
complete -c wuzz -n '__fish_seen_subcommand_from -k' -s 1 -l tlsv1 -d 'Forces TLS version 1.x (1.0, 1.1 or 1.2)'
complete -c wuzz -n __fish_no_arguments -s v -l version -d 'Display version number'
complete -c wuzz -n '__fish_seen_subcommand_from -k' -s x -l proxy -d 'URL          Set HTTP(S) or SOCKS5 proxy'
complete -f -c wuzz -n __fish_use_subcommand -a -R -d '--disable-redirects  Do not follow HTTP redirects'
complete -c wuzz -n '__fish_seen_subcommand_from -R' -s c -l config -d 'PATH        Specify custom configuration file'
complete -c wuzz -n '__fish_seen_subcommand_from -R' -s e -l editor -d 'EDITOR      Specify external editor command'
complete -c wuzz -n '__fish_seen_subcommand_from -R' -s f -l file -d 'REQUEST       Load a previous request'
complete -c wuzz -n '__fish_seen_subcommand_from -R' -s F -l form -d 'DATA          Add multipart form request data and set related request headers'
complete -c wuzz -n '__fish_seen_subcommand_from -R' -s h -l help -d 'Show this'
complete -c wuzz -n '__fish_seen_subcommand_from -R' -s j -l json -d 'JSON          Add JSON request data and set related request headers'
complete -c wuzz -n '__fish_seen_subcommand_from -R' -s k -l insecure -d 'Allow insecure SSL certs'
complete -c wuzz -n '__fish_seen_subcommand_from -R' -s R -l disable-redirects -d 'Do not follow HTTP redirects'
complete -c wuzz -n '__fish_seen_subcommand_from -R' -s T -l tls -d 'MIN,MAX        Restrict allowed TLS versions (values: SSL3.0,TLS1.0,TLS1.1,TLS1.2)'
complete -c wuzz -n '__fish_seen_subcommand_from -R' -s 1 -l tlsv1 -d 'Forces TLS version 1.x (1.0, 1.1 or 1.2)'
complete -c wuzz -n __fish_no_arguments -s v -l version -d 'Display version number'
complete -c wuzz -n '__fish_seen_subcommand_from -R' -s x -l proxy -d 'URL          Set HTTP(S) or SOCKS5 proxy'
complete -f -c wuzz -n __fish_use_subcommand -a -T -d '--tls MIN,MAX        Restrict allowed TLS versions (values: SSL3.0,TLS1.0,TLS1.1,TLS1.2)'
complete -c wuzz -n '__fish_seen_subcommand_from -T' -s c -l config -d 'PATH        Specify custom configuration file'
complete -c wuzz -n '__fish_seen_subcommand_from -T' -s e -l editor -d 'EDITOR      Specify external editor command'
complete -c wuzz -n '__fish_seen_subcommand_from -T' -s f -l file -d 'REQUEST       Load a previous request'
complete -c wuzz -n '__fish_seen_subcommand_from -T' -s F -l form -d 'DATA          Add multipart form request data and set related request headers'
complete -c wuzz -n '__fish_seen_subcommand_from -T' -s h -l help -d 'Show this'
complete -c wuzz -n '__fish_seen_subcommand_from -T' -s j -l json -d 'JSON          Add JSON request data and set related request headers'
complete -c wuzz -n '__fish_seen_subcommand_from -T' -s k -l insecure -d 'Allow insecure SSL certs'
complete -c wuzz -n '__fish_seen_subcommand_from -T' -s R -l disable-redirects -d 'Do not follow HTTP redirects'
complete -c wuzz -n '__fish_seen_subcommand_from -T' -s T -l tls -d 'MIN,MAX        Restrict allowed TLS versions (values: SSL3.0,TLS1.0,TLS1.1,TLS1.2)'
complete -c wuzz -n '__fish_seen_subcommand_from -T' -s 1 -l tlsv1 -d 'Forces TLS version 1.x (1.0, 1.1 or 1.2)'
complete -c wuzz -n __fish_no_arguments -s v -l version -d 'Display version number'
complete -c wuzz -n '__fish_seen_subcommand_from -T' -s x -l proxy -d 'URL          Set HTTP(S) or SOCKS5 proxy'
complete -c wuzz -s 1 -l tlsv1 -d 'Forces TLS version 1.x (1.0, 1.1 or 1.2)'
complete -c wuzz -n __fish_no_arguments -s v -l version -d 'Display version number'
complete -c wuzz -s x -l proxy -d 'URL          Set HTTP(S) or SOCKS5 proxy'
