complete -c yj -s yy -d '= YAML to YAML'
complete -c yj -s yt -d '= YAML to TOML'
complete -c yj -s yc -d '= YAML to HCL'
complete -c yj -s ty -d '= TOML to YAML'
complete -c yj -s tt -d '= TOML to TOML'
complete -c yj -s tc -d '= TOML to HCL'
complete -c yj -s jj -d '= JSON to JSON'
complete -c yj -s jt -d '= JSON to TOML'
complete -c yj -s jc -d '= JSON to HCL'
complete -c yj -s cy -d '= HCL to YAML'
complete -c yj -s ct -d '= HCL to TOML'
complete -c yj -s cc -d '= HCL to HCL'
complete -c yj -s n -d 'Do not covert inf, -inf, and NaN to/from strings (YAML in/out only)'
complete -c yj -s e -d 'Escape HTML (JSON out only)'
complete -c yj -s i -d 'Indent output (JSON or TOML out only)'
complete -c yj -s k -d 'Attempt to parse keys as objects or numbers types (YAML out only)'
complete -c yj -s h -d 'Show this help message'
